project:
  type: website
  output-dir: docs

website:
  title: "Paula Scholz"
  search: false

  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - cv.qmd
    background: light
  

format:
  html:
    theme: superhero
    css: styles.css
    toc: false
    fontcolor: white



