---
title: "Research"
format: html
resources: Scholz_Leadership_and_the_Gender_Application_Gap_August2026.pdf Universitaet zu Koeln Logo.jpg

include-in-header:
  - text: |
     <link rel = "icon" type = "image/png" href = "Universitaet zu Koeln Logo.jpg" />

---

### Working Papers

<strong>It's Not About the Money - Or Is It? Leadership and the Gender Application Gap</strong>  <br><i> <small> Single-authored </i></small></br>
<details>
  <summary>Abstract</summary>
  <p style="text-align: justify;"><small> 
A key supply-side factor contributing to gender gaps in pay and representation in leadership is a gender gap in applications for those positions. With salaries becoming increasingly observable at the application stage, understanding the role of different salary levels in application behavior is important. Using a laboratory experiment, I i) study the role of different salary levels on the gender application gap, ii) examine underlying mechanisms and iii) test a potential solution to mitigate any salary-induced gender application gap. I find a substantial gender gap in the willingness to apply only for highly paid positions: women are 12% less willing to pay than men to acquire these roles despite performing equally well as leaders. While risk attitudes and confidence do not drive the application gap, I find that the gender difference can be explained by men's general higher willingness to claim the lead, which is salary-dependent and gets activated for high salary positions. Additionally, the high salary position is associated with a shift in the perceived stereotype about leadership from female-typed to male-typed, especially among men. Randomly assigning prior leadership experience, a potential solution, does on average not reduce 
the gender application gap.</small> 
</p>
</details>



- <a target="_blank" href="Scholz_Leadership_and_the_Gender_Application_Gap_August2026.pdf"><small> Current Version </small> </a>

### Work in Progress


<strong>Gender Discrimination against Pre-PhD Students: Evidence from a Field
Experiment</strong> <br> <i> <small> with <a target="_blank" href="https://www.bwl.uni-mannheim.de/en/doerrenberg/team/prof-dr-philipp-doerrenberg/">Philipp Dörrenberg</a> and <a target="_blank" href="https://scholar.google.com/citations?user=mXe3h70AAAAJ&hl=de">Christoph Feldhaus</a> </i></small>

- <small>Data collection completed </small> 
- <small>Manuscript in preparation </small> 


<strong>Onboarding, Matching, and Employee Turnover - A Field Experiment</strong> <br> <i> <small> with <a target="_blank" href="https://dsliwka.github.io/">Dirk Sliwka</a> and <a target="_blank" href="https://sites.google.com/site/vogelsangtimo/">Timo Vogelsang</a> </i></small> </br>
<details>
  <summary>Abstract</summary>
  <p style="text-align: justify;"> <small>  We evaluate how a low-cost onboarding practice at the beginning of the employment
affects turnover among newly hired frontline employees. In partnership with a large German
retail chain, we ran a field experiment across more than 900 stores and 2371 new hires (August
2024 - July 2025). Treated stores implemented a structured welcome intervention: managers
announced the newcomer in advance and hosted a brief social event with their colleagues
on the first day, while control stores continued with business-as-usual onboarding. The
intervention increases separations in the first month of employment by about 2 percentage
points while cumulative separations over three and six months are largely unchanged, in line
with the view that the intervention accelerates mutual learning about match quality. Both
stayers and movers in the treatment group have higher working hours indicating that the
treatment also fostered employee motivation.</small> 
</p>
</details>

- <small>Data collection completed </small> 
- <small>Draft available upon request </small> 



<strong>AI or human? Applicants’ decisions in discrimination settings</strong> <br> <i> <small> with <a target="_blank" href="https://economics.uni-koeln.de/de/team/doctoral-students/luisa-santiago-wolf">Luisa Santiago Wolf</a> and <a target="_blank" href="https://cd.wiso.uni-koeln.de/en/team/strategic-management/david-stommel">David Stommel</a> </i> </small> </br>

- <small> Manuscript in preparation</small> 
- <a target="_blank" href="https://www.queb.org/blog/ki-im-recruiting/"><small> Queb Blog Post</small> </a>

<strong>Building Better Managers for the Future of Work</strong> <br> <i> <small>with <a target="_blank" href="https://www.daviddeming.com/">David J. Deming</a>,  <a target="_blank" href="https://sites.google.com/site/josephvecci/home">Joe Vecci</a>, and <a target="_blank" href="https://www.benweidmann.org/">Ben Weidmann</a> </i> </small> </br>

- <small> Design stage</small> 



